### ISSUE TITLE
Failed to launch chrome

### ISSUE THREAD

**Issue by TMInnovations** [christopher-talke/node-express-puppeteer-pdf-example#2]
Hey there,

just wanted to play around with your repo a bit. After starting up the docker image and trying to "Click here to print this page" the server complained with:
```
GET /generate-pdf?url=http://localhost:3000 - - ms - -
(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/app/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

I'd really like to see it workig. Could you maybe add the dependencies needed (libXtst.so.6)?

Thanks and all the best, 
Thomas

**Comment by christopher-talke** [comment]
Saw you created a pull request, closing this issue.

Thanks again.
